  github:
    token: ${GITHUB_TOKEN}

  openai:
    api_key: ${OPENAI_API_KEY}

  review:
    max_files: 5
    file_extensions:
      - .py
      - .js
      - .ts

  ai:
    model: gpt-3.5-turbo
    temperature: 0.7
    max_tokens: 500

  prompts:
    code_review: |
      You are a code reviewer. Analyze the following code diff and provide constructive feedback:
      
      {code_diff}
      
      Focus on:
        1. Code quality
        2. Potential bugs
        3. Performance issues
        4. Best practices